services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: devopsdb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops -d devopsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: nginx:alpine

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:80"
