name: DevOps CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t devops-demo ./docker-demo

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name devops-demo devops-demo

      - name: Test application
        run: curl --fail http://localhost:8080

      - name: Stop container
        if: always()
        run: docker stop devops-demo
