name: DevOps CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t devops-demo ./docker-demo

      - name: List Docker images
        run: docker images
